name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./src/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build front-end
        run: npx webpack --mode production

      - name: TypeCheck front-end
        run: npm run typeCheck

        # See https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Set time zone to America/Chicago
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Chicago"
          timezoneMacos: "America/Chicago"
          timezoneWindows: "America/Chicago"

      - name: Run JS test suite
        run: |
          npm run unitTests -- --maxWorkers ${{ steps.cpu-cores.outputs.count }} --coverage --coverageReporters json-final

      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main
